config_created: '2020-03-13 14:15:06.929136'
config_updated: '2020-03-13 19:12:39.880677'
data_dir: data/simulation/simulation_data
fdata_delim: ','
fdata_head:
  freq_hz: freq [Hz]
  phase_rad: phase_angle [rad]
  r_imag_ohm: Im_Z [Ohm]
  r_real_ohm: Re_Z [Ohm]
  r_totl_ohm: '|Z| [Ohm]'
file_type: .csv
header_end_str: '---'
header_meta:
  circuit_detail: 'Circuit elements:'
  circuit_str: 'Cirucit type:'
  d_source: 'Data Source:'
  date_run: 'Date:'
  serial_n: 'Serial number:'
